### ISSUE TITLE
Large number of gifs

### ISSUE THREAD

**Issue by lucymonie** [FAC10/week3-PAMF#76]
In some cases there are so many gifs that it's doesn't fit on the screen, so there's a ton of scrolling around. This seems like a game that should be aimed at bored commuters so maybe one gif per word would be better so it could fit on a phone screen?

**Comment by pbywater** [comment]
Yeah I completely agree - problem is that giphy gives some VERY rogue gifs so even with three per word it is very tricky! That's why we didn't want to cut it down. We might put a limit on the word count of films to try and help with the issue and need to do some mobile optimisation too. Thanks for the feedback :)
